<?php

$titre = array(
    "<h2>Comment déguster un vin ?/h2>",
    "<h2>How to taste a wine?</h2>"
);

$para1 = array(
    "<p>Pour déguster le vin, il existe plusieurs étapes à suivre qui font appel à trois sens différents qui sont : la vue, l’odorat ainsi que le goût.</p><p>La première étape consiste à regarder le verre de vin. Tout d’abord, regardez la robe du vin (sa couleur, son apparence) qui vous donnera des indications sur la nature ainsi que la qualité du vin. Pour se faire, penchez légèrement votre verre, bras tendu à l’horizontale et observez la robe du vin. Regarder le vin comme ceci permettra de déterminer la qualité sanitaire du vin. En effet, par exemple, l’intensité de la couleur d’un vin rouge ainsi que sa limpidité, sont des indices de la bonne qualité du vin. L’examen visuel ne s'arrête pas là, car en faisant tourner le vin, on peut observer la viscosité de ce dernier. Cela permettra de déduire si le vin en question contient plus d’alcool s’il est fluide ou de sucre s’il est épais et gras.</p>",
    "<p>To taste wine, there are several steps to follow which involve three different senses which are: sight, smell as well as taste.</p><p>The first step is to look at the wine glass. First of all, look at the colour of the wine (its colour, its appearance) which will give you indications on the nature as well as the quality of the wine. To do this, tilt your glass slightly with your arm extended horizontally and observe the colour of the wine. Looking at the wine like this will help determine the sanitary quality of the wine. Indeed, for example, the intensity of colour of a red wine, as well as its clarity, are indications of the good quality of the wine. The visual examination does not stop there, because by rotating the wine, one can observe its viscosity. This will help to deduce whether the wine in question contains more alcohol if it is fluid or sugar if it is thick and fatty.</p>"
);

$para2 = array(
    "<p>La seconde étape consiste à sentir le vin.</p><p>Sentir le vin permet d’avoir un aperçu de la saveur du vin. Il faut tout d'abord sentir le vin sans bouger le vin, il s’agit du premier nez. Suivant le vin que vous sentez, il peut être fermé (on ne sent rien), discret ou ouvert. Si le vin est fermé, vous pouvez le carafé afin de l’ouvrir. Suite à cela, faites tourner le vin et humez-le, il s’agit du deuxième nez. Puis fermez les yeux afin de ressentir chaque arôme.</p>",
    "<p>The second step is to smell the wine.</p> <p>Smelling the wine gives you an insight into the flavour of the wine. The first step is to smell the wine without moving the wine, this is the first nose. Depending on the wine you smell, it can be closed (you don't smell anything), discrete or open. If the wine is closed, you can decant it to open it up. After that, rotate the wine and smell it, this is the second nose. Then close your eyes to smell each aroma.</p>"
);

$para3 = array(
    "<p>La dernière étape consiste à la dégustation.</p><p>Beaucoup de professionnels recrachent le vin afin de garder le palais et les idées claires. Si vous débutez, vous risquez d’avoir du mal à bien percevoir le vin que vous recrachez en totalité et vous aurez sans doute le sentiment de ne pas pleinement profiter de ce vin. Commencez à avaler quelques gorgées recrachez en d'autres. Ainsi, au fur et à mesure, vous pourrez recracher de plus en plus. </p>",
    "<p>The final step is tasting.</p><p>Many professionals spit out the wine in order to keep their palate and mind clear. If you are just starting out, you may have trouble getting a good feel for the wine you are spitting out in its entirety, and you may feel that you are not fully enjoying the wine. Start by swallowing a few sips and spit out others. This way, as you go along, you can spit out more and more. </p>"
);

$para4 = array(
    "<p>&nbsp &nbsp &nbsp Une fois le vin en bouche, vous allez chercher l’équilibre du vin qui est différent en fonction du vin dégusté.</p><p>&nbsp &nbsp &nbsp Dans un vin blanc, vous trouverez l’équilibre entre deux dimensions, l’acidité ainsi que le gras du vin. L’acidité est assez simple à repérer par habitude de le percevoir. Le gras du vin est quant à lui plus difficile à repérer. Il peut se définir par la douceur du vin, une sensation agréable, suave, de rondeur et d’onctuosité.</p><p>&nbsp &nbsp &nbspLe vin rouge, tout comme le vin blanc, présente l’acidité et gras comme dimension pour trouver l’équilibre, mais, on ajoute une nouvelle dimension pour ce vin, les tanins. Les tanins se ressentent non pas par une sensation de “goût” mais par une sorte de poudre au milieu de la langue ce qui donne une sensation de “sec”.</p><p>&nbsp &nbsp &nbspL’équilibre du vin s'apprécie de façon à reconnaître si les dimensions s’accordent bien entre elles afin de reconnaître un équilibre entre ces dimensions. </p><p>&nbsp &nbsp &nbspLa dégustation du vin de champagne est quant à elle différente de celle d’un vin “classique”. En effet, comparé aux autres vins, le champagne est effervescent et laisse donc découvrir de nouvelles sensations au niveau du nez et de la bouche. </p>",
    "<p>&nbsp &nbsp &nbsp Once the wine is in your mouth, you will look for the balance of the wine which is different depending on the wine tasted.</p><p>&nbsp &nbsp &nbsp In a white wine, you will find the balance between two dimensions, the acidity as well as the fatness of the wine. The acidity is quite simple to spot by habit of perception. The fatness of the wine is more difficult to spot. It can be defined by the softness of the wine, a pleasant, suave sensation of roundness and unctuousness.</p><p>&nbsp &nbsp &nbspRed wine, just like white wine, presents acidity and fat as a dimension to find balance, but, we add a new dimension for this wine, the tannins. Tannins are felt not by a \"taste\" sensation but by a kind of powder in the middle of the tongue which gives a \"dry\" sensation.</p><p>&nbsp &nbsp &nbspThe balance of the wine is appreciated in a way to recognize if the dimensions fit well together in order to recognize a balance between these dimensions. </p><p>&nbsp &nbsp &nbspThe tasting of champagne wine is different from that of a \"classic\" wine. Indeed, compared to other wines, champagne is effervescent and therefore lets you discover new sensations in the nose and mouth. </p>"
);


$para5 = array(
    "<p>&nbsp &nbsp &nbspTout comme les autres vins, il y a trois étapes à passer pour déguster un champagne qui est similaire à quelques détails près des vins non-effervescents.</p><p>&nbsp &nbsp &nbspLorsque vous regardez votre verre, vous allez analyser les bulles et leurs finesses ainsi que sa couleur.</p><p>&nbsp &nbsp &nbsp Pour le nez, évitez de prendre une trop grosse inspiration pour ne pas ressentir que le gaz qui s’échappe du verre. Prenez une petite respiration au-dessus du verre pour ressentir tous ses arômes. Inutile de faire tourner votre verre pour agiter le vin, les bulles agitent le champagne et font tout ce qu’il faut.</p><p>&nbsp &nbsp &nbsp Enfin en bouche n’essayez pas de le recracher comme les vins sans bulles, prenez simplement de petites gorgées ce qui limitera l’effet perturbant de l’effervescence sur votre palet et vous permettra donc de mieux apprécier ses arômes et goûts. Afin de trouver l’équilibre comme dans les autres vins, on ajoute à cela la finesse des bulles qui peuvent rendre plus difficile de détecter les saveurs par rapport à un vin tranquille.</p><br>",
    "<p>&nbsp &nbsp &nbspLike other wines, there are three steps to tasting a champagne that is similar to non-sparkling wines in a few details.</p><p>&nbsp &nbsp &nbspWhen you look at your glass, you will analyse the bubbles and their fineness as well as its colour.</p><p>&nbsp &nbsp &nbspFor the nose, avoid taking too much of a breath so you don't just feel the gas escaping the glass. Take a small breath over the glass to feel all its aromas. There is no need to swirl your glass to shake the wine, the bubbles shake the champagne and do all the right things.</p><p>&nbsp &nbsp &nbsp Finally in the mouth don't try to spit it out like wines without bubbles, just take small sips which will limit the disturbing effect of the effervescence on your palate and thus allow you to better appreciate its aromas and tastes. In order to find the balance as in other wines, we add to this the fineness of the bubbles which can make it more difficult to detect the flavours compared to a still wine.</p><br>"
);
